import type { ButtonHTMLAttributes, PropsWithChildren } from 'react';
import { HexColorPicker } from 'react-colorful';
import { Palette } from 'lucide-react';
import { Popover, Slider, ToggleGroup } from 'radix-ui';

type ButtonProps = ButtonHTMLAttributes<HTMLButtonElement> & { variant?: 'primary' | 'secondary' | 'ghost'; loading?: boolean; size?: 'default' | 'compact' | 'icon' };
export function Button({ variant = 'secondary', size = 'default', loading, className = '', children, disabled, ...props }: PropsWithChildren<ButtonProps>) {
  const styles = {
    primary: 'bg-[#f5f5f5] text-[#0d0d0d] shadow-[inset_0_1px_0_rgba(255,255,255,.5),inset_0_0_0_1px_rgba(255,255,255,.12),0_1px_2px_rgba(0,0,0,.45)] hover:bg-white hover:shadow-[inset_0_1px_0_rgba(255,255,255,.6),inset_0_0_0_1px_rgba(255,255,255,.14),0_2px_6px_rgba(0,0,0,.5)] active:bg-[#dcdcdc] active:shadow-[inset_0_1px_2px_rgba(0,0,0,.16)] disabled:bg-[#3a3a3a] disabled:text-[#777] disabled:shadow-none',
    secondary: 'bg-white/[.06] text-[#dcdcdc] shadow-[inset_0_0_0_1px_rgba(255,255,255,.06),inset_0_1px_0_rgba(255,255,255,.06)] hover:bg-white/[.09] hover:text-white hover:shadow-[inset_0_0_0_1px_rgba(255,255,255,.09),inset_0_1px_0_rgba(255,255,255,.08)] active:bg-white/[.05] active:shadow-[inset_0_1px_2px_rgba(0,0,0,.3)] disabled:text-[#5c5c5c] disabled:shadow-none',
    ghost: 'text-[#8a8a8a] hover:bg-white/[.06] hover:text-white active:bg-white/[.04] disabled:text-[#4a4a4a]',
  };
  const sizes = { default: 'h-8 px-3', compact: 'h-7 px-2.5', icon: 'size-8 p-0' };
  return <button className={`inline-flex cursor-pointer select-none items-center justify-center gap-2 rounded-lg border-0 text-[11px] font-medium tracking-[.005em] outline-none transition-[background-color,color,box-shadow,transform] duration-100 focus-visible:shadow-[0_0_0_2px_#0a0a0a,0_0_0_3.5px_rgba(255,255,255,.4)] active:scale-[.985] disabled:cursor-not-allowed disabled:active:scale-100 ${styles[variant]} ${sizes[size]} ${className}`} disabled={disabled || loading} {...props}>{children}</button>;
}
export function ValueSlider({ label, value, min, max, step = 1, format, onChange }: { label: string; value: number; min: number; max: number; step?: number; format: (value: number) => string; onChange: (value: number) => void }) {
  return <div className="space-y-1.5"><div className="flex items-center justify-between text-[10px]"><span className="text-zinc-500">{label}</span><output className="font-medium tabular-nums text-zinc-300">{format(value)}</output></div><Slider.Root value={[value]} min={min} max={max} step={step} onValueChange={([next]) => onChange(next)} className="relative flex h-[30px] w-full cursor-pointer touch-none select-none items-center px-0.5"><Slider.Track className="relative h-2.5 w-full grow overflow-hidden rounded-[3px] border border-white/[.08] bg-black/30"><Slider.Range className="absolute h-full bg-white/[.14]" /></Slider.Track><Slider.Thumb aria-label={label} className="block h-6 w-2 cursor-grab rounded-[2px] border border-white/50 bg-[#e6e6e1] shadow-[0_1px_2px_rgba(0,0,0,.5)] outline-none focus-visible:ring-1 focus-visible:ring-zinc-100 focus-visible:ring-offset-2 focus-visible:ring-offset-[#0a0a0a] active:cursor-grabbing" /></Slider.Root></div>;
}
export function ChoiceGroup({ value, onChange, children, columns = 3 }: PropsWithChildren<{ value: string; onChange: (value: string) => void; columns?: number }>) { return <ToggleGroup.Root type="single" value={value} onValueChange={(next) => next && onChange(next)} className="grid gap-1.5" style={{ gridTemplateColumns: `repeat(${columns}, minmax(0,1fr))` }}>{children}</ToggleGroup.Root>; }
export function ChoiceItem({ value, children, label }: PropsWithChildren<{ value: string; label: string }>) { return <ToggleGroup.Item value={value} aria-label={label} className="group flex min-h-14 cursor-pointer flex-col items-center justify-center gap-1.5 rounded-lg border-0 bg-white/[.05] px-1 py-2 text-[10px] font-medium text-[#9a9a9a] shadow-[inset_0_0_0_1px_rgba(255,255,255,.05),inset_0_1px_0_rgba(255,255,255,.05)] outline-none transition-[background-color,color,box-shadow] duration-100 hover:bg-white/[.09] hover:text-[#dcdcdc] hover:shadow-[inset_0_0_0_1px_rgba(255,255,255,.08),inset_0_1px_0_rgba(255,255,255,.07)] active:bg-white/[.05] active:shadow-[inset_0_1px_2px_rgba(0,0,0,.3)] focus-visible:shadow-[0_0_0_2px_#0a0a0a,0_0_0_3.5px_rgba(255,255,255,.35)] data-[state=on]:bg-[#f5f5f5] data-[state=on]:text-[#0d0d0d] data-[state=on]:shadow-[0_1px_2px_rgba(0,0,0,.4),inset_0_1px_0_rgba(255,255,255,.4)]">{children}<span>{label}</span></ToggleGroup.Item>; }
export function ColorField({ value, active, onChange }: { value: string; active: boolean; onChange: (value: string) => void }) {
  return <Popover.Root><Popover.Trigger asChild><button type="button" aria-label="自定义背景颜色" className={`h-10 cursor-pointer rounded-[6px] border p-1 transition-colors ${active ? 'border-zinc-300' : 'border-white/10 hover:border-white/25'}`}><span className="grid h-full place-items-center rounded-[3px] border border-white/10" style={{ background: value }}><Palette className="size-3 text-white/80" /></span></button></Popover.Trigger><Popover.Portal><Popover.Content side="left" align="start" sideOffset={12} className="z-30 origin-[var(--radix-popover-content-transform-origin)] animate-[popover-in_120ms_ease-out] rounded-[7px] border border-white/10 bg-[#141414] p-3 shadow-xl outline-none"><HexColorPicker color={value} onChange={onChange} style={{ width: 216, height: 160 }} /><div className="mt-2 text-center font-mono text-[11px] uppercase text-zinc-500">{value}</div><Popover.Arrow className="fill-[#141414]" /></Popover.Content></Popover.Portal></Popover.Root>;
}
